image: alpine:latest

clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          script:
            # install git
            - apk add --no-cache git
            # deploy master branch to heroku
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
